config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers:{
  registrations: "users/registrations",
  omniauth_callbacks:"users/omniauth_callbacks"
}
  resources :topics,only:[:index, :new, :create, :edit, :update, :destroy, :show]

  resources :topics do
    resources :comments
    post :confirm, on: :collection
  end

  resources :users,only:[:index,:show]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end

  get 'topics' => "topics#index"
  root 'top#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    validates :content, presence: true
    belongs_to :user
    has_many :comments, dependent: :destroy
    mount_uploader :imageurl, ImageurlUploader
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic,only:[:edit, :update, :destroy,:show]

  def index
    @topics = Topic.all
     respond_to do |format|
    format.html
    format.js
    end
  end


  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
    redirect_to topics_path, notice: "投稿しました"
    NoticeMailer.sendmail_topic(@topic).deliver
    else
    render 'new'
    end
  end

  def edit
  end

  def update
    @topic.update(topics_params)
    redirect_to topics_path, notice:"編集しました"
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice:"削除しました"
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  private
   def topics_params
     params.require(:topic).permit(:content,:imageurl, :imageurl_cache)
   end

   def set_topic
     @topic = Topic.find(params[:id])
     if @topic.user_id != current_user.id
        redirect_to root_path, alert: "通報しました。"
        return
    end
   end
 end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :内容 %>
  <%= f.text_field :content,class: 'form-control input-lg',placeholder: "今何してる？" %>
  <br>
  <%= f.label :写真 %>
  <%= f.file_field :imageurl %>
  <%= f.hidden_field :imageurl_cache %>
  <%= f.submit'投稿',class:'btn btn-primary btn-sm active' %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", topics_path %>

app/views/topics/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

    <%= render 'form' %>
 
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
 <p class="flash"><%= notice %><%= alert %></p>

    <h1>投稿一覧</h1>
    <%= link_to "投稿", new_topic_path, class: 'btn btn-default' %>
    <br>
    <% @topics.each do |topic| %>

    <div class="row">
      <br>
      <h3><%=topic.user.name if topic.user %></h3>

       <%= link_to topic_path(topic) do %>
        <% end %>
     <p>本文: <%= link_to topic.content,topic_path(topic.id) %></p>
     <%= image_tag topic.imageurl,:class => "image_url" %>
    <%= link_to "編集", edit_topic_path(topic.id),class: 'btn btn-primary btn-sm active' %>
    <%= link_to "削除",topic_path(topic.id), method: :delete, data:{
    confirm: "本当に削除していいですか?"},class: 'btn btn-primary btn-sm active' %>
    </div>
    <% end %>

  </div>
 </div>

app/views/topics/new.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

    <%= render 'form' %>
 </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <p class="center"><strong>投稿者:</strong></p>
      <p class="center"><%= @topic.user.name %></p>
      <br>
      <p class="left"><strong>内容:</strong></p>
      <p class="left"><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', topics_path %>
  </div>
</div>