config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers:{
  registrations: "users/registrations",
  omniauth_callbacks:"users/omniauth_callbacks"
}
  resources :topics,only:[:index, :new, :create, :edit, :update, :destroy, :show]

  resources :topics do
    resources :comments
    post :confirm, on: :collection
  end

  resources :users,only:[:index,:show]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end

  get 'topics' => "topics#index"
  root 'top#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nyanbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
   <header>
        <img class="logo" src="<%= asset_path "facebook.png" %>">
      <ul>
      <li><%= link_to "トップページ", new_topic_path %></li>
       <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
        <% if user_signed_in? %>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path  %></li>
          <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <% end %>
       </ul>
    </header>

<%= yield %>
　　<footer>
    <p>運営会社Yamaneko株式会社</p>
    <p>© 2015-2016 Copyright Yamaneko Corp.</p>
  　</footer>

</body>
</html>